// Mock-данные для фронтенда

const mockPairs = [
  { id: 1, name: 'BTC/USDT', price: '68,123.10', change24h: -1.2 },
  { id: 2, name: 'ETH/USDT', price: '3,500.50', change24h: 2.5 },
  { id: 3, name: 'BNB/USDT', price: '600.25', change24h: 1.8 },
  { id: 4, name: 'SOL/USDT', price: '150.20', change24h: 5.1 },
  { id: 5, name: 'XRP/USDT', price: '0.52', change24h: -0.7 },
  { id: 6, name: 'ADA/USDT', price: '0.45', change24h: 3.2 },
  { id: 7, name: 'DOGE/USDT', price: '0.158', change24h: -3.4 },
  { id: 8, name: 'SHIB/USDT', price: '0.000025', change24h: 7.1 },
  { id: 9, name: 'DOT/USDT', price: '7.80', change24h: 0.9 },
  { id: 10, name: 'AVAX/USDT', price: '35.10', change24h: -2.1 },
  { id: 11, name: 'LINK/USDT', price: '14.50', change24h: 4.0 },
  { id: 12, name: 'LTC/USDT', price: '75.30', change24h: -1.5 },
  { id: 13, name: 'BCH/USDT', price: '450.00', change24h: 2.8 },
  { id: 14, name: 'UNI/USDT', price: '8.90', change24h: 1.1 },
  { id: 15, name: 'MATIC/USDT', price: '0.72', change24h: -0.5 },
  { id: 16, name: 'ICP/USDT', price: '12.00', change24h: 6.0 },
  { id: 17, name: 'ETC/USDT', price: '28.50', change24h: -0.9 },
  { id: 18, name: 'XLM/USDT', price: '0.11', change24h: 0.3 },
  { id: 19, name: 'VET/USDT', price: '0.035', change24h: 1.6 },
  { id: 20, name: 'TRX/USDT', price: '0.105', change24h: -0.2 },
];

const mockPosts = [
  // Popular posts (10 posts)
  {
    id: 1, type: 'popular',
    author: { name: 'CryptoBull', address: '0x123...abc' },
    timestamp: '2 часа назад',
    content: 'BTC готовится к новому рывку! Луна не предел. 🚀',
    likes: 125, views: 1200,
    image: import.meta.env.BASE_URL + 'img/Account.svg',
  },
  {
    id: 2, type: 'popular',
    author: { name: 'Аналитик_80', address: '0x456...def' },
    timestamp: '5 часов назад',
    content: 'Не забывайте про диверсификацию. Альткоины показывают силу, особенно в секторе AI.',
    likes: 88, views: 950,
    image: import.meta.env.BASE_URL + 'img/453ц 1.svg',
  },
  {
    id: 3, type: 'popular',
    author: { name: 'DeFi_Guru', address: '0x789...ghi' },
    timestamp: '1 день назад',
    content: 'Мой прогноз по ETH на конец года: $5000. Что думаете?',
    likes: 210, views: 1800,
    video: 'https://www.youtube.com/embed/dQw4w9WgXcQ', // Example video
  },
  {
    id: 10, type: 'popular',
    author: { name: 'TraderX', address: '0x111...222' },
    timestamp: '1 день назад',
    content: 'Рынок сегодня очень волатилен. Будьте осторожны с плечами!',
    likes: 50, views: 700,
    image: import.meta.env.BASE_URL + 'img/_more_.svg',
  },
  {
    id: 11, type: 'popular',
    author: { name: 'Blockchain_Enthusiast', address: '0x222...333' },
    timestamp: '2 дня назад',
    content: 'Изучаю новые протоколы Layer 2. Какие проекты посоветуете?',
    likes: 70, views: 900,
    image: import.meta.env.BASE_URL + 'img/1672306520_kalix-club-p-kosmos-zastavka-na-aifon-krasivo-49 1.svg',
  },
  {
    id: 12, type: 'popular',
    author: { name: 'NFT_Artist', address: '0x333...444' },
    timestamp: '3 дня назад',
    content: 'Моя новая коллекция NFT уже на OpenSea! Зацените.',
    likes: 180, views: 2000,
    image: import.meta.env.BASE_URL + 'img/3452 1.png',
  },
  {
    id: 13, type: 'popular',
    author: { name: 'Degen_Ape', address: '0x444...555' },
    timestamp: '4 дня назад',
    content: 'Продал все свои шиткоины, перешел в стейблы. Жду коррекции.',
    likes: 30, views: 500,
    image: import.meta.env.BASE_URL + 'img/56е43 1.svg',
  },
  {
    id: 14, type: 'popular',
    author: { name: 'Smart_Investor', address: '0x555...666' },
    timestamp: '5 дней назад',
    content: 'Долгосрочные инвестиции в BTC и ETH - лучшая стратегия.',
    likes: 250, views: 3000,
    image: import.meta.env.BASE_URL + 'img/--------.svg',
  },
  {
    id: 15, type: 'popular',
    author: { name: 'Crypto_News', address: '0x666...777' },
    timestamp: '6 дней назад',
    content: 'Последние новости из мира криптовалют: регуляция и инновации.',
    likes: 100, views: 1500,
    image: import.meta.env.BASE_URL + 'img/-------------- (1).svg',
  },
  {
    id: 16, type: 'popular',
    author: { name: 'Mining_Master', address: '0x777...888' },
    timestamp: '7 дней назад',
    content: 'Моя ферма работает на полную мощность! Кто еще майнит?',
    likes: 60, views: 800,
    image: import.meta.env.BASE_URL + 'img/-------------- (2).svg',
  },

  // Hot posts (10 posts)
  {
    id: 4, type: 'hot',
    author: { name: 'Blockchain_Dev', address: '0xabc...jkl' },
    timestamp: '30 минут назад',
    content: 'Только что развернул новый смарт-контракт на Polygon. Газ копейки!',
    likes: 50, views: 300,
    image: import.meta.env.BASE_URL + 'img/_more_1.svg',
  },
  {
    id: 5, type: 'hot',
    author: { name: 'NFT_Collector', address: '0xdef...mno' },
    timestamp: '1 час назад',
    content: 'Приобрел редкий NFT из коллекции "PixelPunks"! #NFT #DigitalArt',
    likes: 75, views: 400,
    image: import.meta.env.BASE_URL + 'img/_more_2.svg',
  },
  {
    id: 8, type: 'hot',
    author: { name: 'DegenTrader', address: '0x111...222' },
    timestamp: '2 часа назад',
    content: 'Шорчу DOGE, кто со мной? 📉',
    likes: 15, views: 100,
    image: import.meta.env.BASE_URL + 'img/_more_3.svg',
  },
  {
    id: 17, type: 'hot',
    author: { name: 'Yield_Max', address: '0x888...999' },
    timestamp: '3 часа назад',
    content: 'Новая стратегия фарминга на BSC. Высокий APR, но есть риски.',
    likes: 40, views: 250,
    image: import.meta.env.BASE_URL + 'img/_more_5.svg',
  },
  {
    id: 18, type: 'hot',
    author: { name: 'Crypto_Analyst', address: '0x999...aaa' },
    timestamp: '4 часа назад',
    content: 'Технический анализ BTC показывает сильное сопротивление на $70k.',
    likes: 90, views: 600,
    image: import.meta.env.BASE_URL + 'img/----------------------.svg',
  },
  {
    id: 19, type: 'hot',
    author: { name: 'DeFi_Builder', address: '0xaaa...bbb' },
    timestamp: '5 часов назад',
    content: 'Разрабатываю новый DApp для кредитования. Скоро бета-тест!',
    likes: 65, views: 350,
    image: import.meta.env.BASE_URL + 'img/---------------------- 1.svg',
  },
  {
    id: 20, type: 'hot',
    author: { name: 'Token_Hunter', address: '0xbbb...ccc' },
    timestamp: '6 часов назад',
    content: 'Нашел гем! Новый токен с низкой капитализацией и огромным потенциалом.',
    likes: 110, views: 800,
    image: import.meta.env.BASE_URL + 'img/-------------------------------------------------- (2) 2.svg',
  },
  {
    id: 21, type: 'hot',
    author: { name: 'Web3_Gamer', address: '0xccc...ddd' },
    timestamp: '7 часов назад',
    content: 'Играю в Axie Infinity. Кто хочет сразиться?',
    likes: 30, views: 200,
    image: import.meta.env.BASE_URL + 'img/-------------------------------------------------- (2) 2 (1).svg',
  },
  {
    id: 22, type: 'hot',
    author: { name: 'DAO_Member', address: '0xddd...eee' },
    timestamp: '8 часов назад',
    content: 'Участвую в голосовании по новому предложению в DAO. Важен каждый голос!',
    likes: 25, views: 180,
    image: import.meta.env.BASE_URL + 'img/2345к23 1.svg',
  },
  {
    id: 23, type: 'hot',
    author: { name: 'Crypto_Educator', address: '0xeee...fff' },
    timestamp: '9 часов назад',
    content: 'Объясняю, что такое блокчейн простыми словами. Задавайте вопросы!',
    likes: 80, views: 500,
    video: 'https://www.youtube.com/embed/yEw_y0g0000', // Another example video
  },

  // Trending posts (10 posts)
  {
    id: 6, type: 'trending',
    author: { name: 'Web3_Innovator', address: '0xfgh...pqr' },
    timestamp: '10 минут назад',
    content: 'Обсуждаем будущее DAO и их роль в управлении децентрализованными проектами.',
    likes: 20, views: 150,
    image: import.meta.env.BASE_URL + 'img/Account.svg',
  },
  {
    id: 7, type: 'trending',
    author: { name: 'Yield_Farmer', address: '0xijk...stu' },
    timestamp: '45 минут назад',
    content: 'Новая фарминг-стратегия на Curve Finance. Доходность 200% APY!',
    likes: 35, views: 250,
    image: import.meta.env.BASE_URL + 'img/453ц 1.svg',
  },
  {
    id: 9, type: 'trending',
    author: { name: 'MetaverseBuilder', address: '0x333...444' },
    timestamp: '1 час назад',
    content: 'Строю свой первый участок земли в Decentraland. Какие идеи для застройки?',
    likes: 40, views: 200,
    image: import.meta.env.BASE_URL + 'img/_more_.svg',
  },
  {
    id: 24, type: 'trending',
    author: { name: 'AI_Crypto', address: '0xfff...000' },
    timestamp: '2 часа назад',
    content: 'Интеграция AI и блокчейна: новые возможности и вызовы.',
    likes: 55, views: 300,
    image: import.meta.env.BASE_URL + 'img/1672306520_kalix-club-p-kosmos-zastavka-na-aifon-krasivo-49 1.svg',
  },
  {
    id: 25, type: 'trending',
    author: { name: 'LayerZero_Fan', address: '0x000...111' },
    timestamp: '3 часа назад',
    content: 'LayerZero - это будущее кроссчейн-коммуникаций. Согласны?',
    likes: 70, views: 400,
    image: import.meta.env.BASE_URL + 'img/3452 1.png',
  },
  {
    id: 26, type: 'trending',
    author: { name: 'ZK_Rollups', address: '0x111...222' },
    timestamp: '4 часа назад',
    content: 'ZK-Rollups меняют правила игры для масштабирования Ethereum.',
    likes: 45, views: 280,
    image: import.meta.env.BASE_URL + 'img/56е43 1.svg',
  },
  {
    id: 27, type: 'trending',
    author: { name: 'GameFi_Expert', address: '0x222...333' },
    timestamp: '5 часов назад',
    content: 'GameFi проекты, за которыми стоит следить в 2025 году.',
    likes: 60, views: 350,
    image: import.meta.env.BASE_URL + 'img/--------.svg',
  },
  {
    id: 28, type: 'trending',
    author: { name: 'RWA_Enthusiast', address: '0x333...444' },
    timestamp: '6 часов назад',
    content: 'Real World Assets (RWA) на блокчейне: революция в финансах.',
    likes: 80, views: 450,
    image: import.meta.env.BASE_URL + 'img/-------------- (1).svg',
  },
  {
    id: 29, type: 'trending',
    author: { name: 'Solana_Dev', address: '0x444...555' },
    timestamp: '7 часов назад',
    content: 'Разрабатываю новый проект на Solana. Скорость транзакций поражает!',
    likes: 50, views: 320,
    image: import.meta.env.BASE_URL + 'img/-------------- (2).svg',
  },
  {
    id: 30, type: 'trending',
    author: { name: 'Cosmos_Builder', address: '0x555...666' },
    timestamp: '8 часов назад',
    content: 'Interchain Security в Cosmos: будущее суверенных блокчейнов.',
    likes: 40, views: 280,
    video: 'https://www.youtube.com/embed/yEw_y0g0000', // Another example video
  },
];

export const getMarketPairs = () => mockPairs;
export const getPosts = (type = 'popular') => {
  if (type === 'all') return mockPosts; // Optional: return all posts
  return mockPosts.filter(post => post.type === type);
};